// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBst_9cXExiQKODMSkODcLaHsJ8FjI-KAg',
    appId: '1:797387905170:web:881e076d81f72501006e4b',
    messagingSenderId: '797387905170',
    projectId: 'tes-mobile-bc2ac',
    authDomain: 'tes-mobile-bc2ac.firebaseapp.com',
    storageBucket: 'tes-mobile-bc2ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3mWMpCKKxfhVTMtTP-l5Sqq8lMOFE7qo',
    appId: '1:797387905170:android:166f55bfe8f3c105006e4b',
    messagingSenderId: '797387905170',
    projectId: 'tes-mobile-bc2ac',
    storageBucket: 'tes-mobile-bc2ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAon28NpVl7PMoFLb_29714HSNAir6YI5g',
    appId: '1:797387905170:ios:ee2be206edf24076006e4b',
    messagingSenderId: '797387905170',
    projectId: 'tes-mobile-bc2ac',
    storageBucket: 'tes-mobile-bc2ac.firebasestorage.app',
    iosBundleId: 'com.example.tesmobilekb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAon28NpVl7PMoFLb_29714HSNAir6YI5g',
    appId: '1:797387905170:ios:ee2be206edf24076006e4b',
    messagingSenderId: '797387905170',
    projectId: 'tes-mobile-bc2ac',
    storageBucket: 'tes-mobile-bc2ac.firebasestorage.app',
    iosBundleId: 'com.example.tesmobilekb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBst_9cXExiQKODMSkODcLaHsJ8FjI-KAg',
    appId: '1:797387905170:web:4d2cfff4ff16a993006e4b',
    messagingSenderId: '797387905170',
    projectId: 'tes-mobile-bc2ac',
    authDomain: 'tes-mobile-bc2ac.firebaseapp.com',
    storageBucket: 'tes-mobile-bc2ac.firebasestorage.app',
  );
}
